### ISSUE TITLE
'validateAndroidProps' of undefined on Android

### ISSUE THREAD

**Issue by jayweb007** [react-native-datetimepicker/datetimepicker#1022]
# Question

TypeError: Cannot read property 'validateAndroidProps' of undefined

getting the above error on react-native "0.78.2" and react native community version 8.0.0 , 8.2.0 and 8.5.0

**Comment by bdtren** [comment]
I'm replicated the issue right now. Have to rollback to 8.4.5 to fix it:
```
yarn add @react-native-community/datetimepicker@8.4.5
```

**Comment by ibm2187** [comment]
it didn't work for me; I got the same error and 
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCDatePicker' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes Error Component Stack:

**Comment by bdtren** [comment]
Hi guys,  
I'm not sure if this will help, but in my case, I updated it because of Google's 16KB memory policy.
I had to update to react-native 0.77.3 and react-native-community/datetimepicker 8.4.5. I also tried with another project that use react native 0.79.2 and it working.
So maybe this fix doesn’t work with react-native versions < 0.77 or >= 0.80?

**Comment by TeyimPila** [comment]
@jayweb007  @bdtren none of these worked for me.

**Comment by soyadrianhurtado** [comment]
Hi guys, I have the same problem.

@react-native-community/datetimepicker": "^8.1.1"
react-native": "0.74.2"

**Comment by rutul089** [comment]
> Hello [@ibm2187](https://github.com/ibm2187) [@TeyimPila](https://github.com/TeyimPila) [@rutul089](https://github.com/rutul089)
> 
> my React Native is 0.78.2 and react-native-community/datetimepicker is 8.5.0 that was previously installed, so, i have to rollback to 8.4.5 to fix it:
> 
> yarn add @react-native-community/datetimepicker@8.4.5
> 
> without uninstall the previous (8.5.0), i just installed the 8.4.5 to replace it.
> 
> All thanks to [@bdtren](https://github.com/bdtren) 💌

I have same config for both but somehow it's not working for me

**Comment by ibm2187** [comment]
I have fixed it by upgrading my CLI versions from 15.something to the latest version (20.0.2) using datetimepicker ^8.4.4

**Comment by Yashveer-Soni** [comment]
> for those who have crash on 8.5.0+ and new arch
> 
> try reverting this commit and patch
> 
> [1ff05e1](https://github.com/react-native-datetimepicker/datetimepicker/commit/1ff05e180817318a99e086643f89ddd4e8ff5549)
> 
> [@react-native-community+datetimepicker+8.6.0.patch](https://github.com/user-attachments/files/24893405/%40react-native-community%2Bdatetimepicker%2B8.6.0.patch)

thanks buddy

**Comment by andhikanovandi** [comment]
For anyone who is still experiencing this issue, try to upgrade the `react-native-community/cli`: https://github.com/react-native-community/cli/pull/2563#issuecomment-2538251494

For me, RN 0.77.3 & datetimepicker 8.6.0, this fix the issue:
```
"@react-native-community/cli": "15.1.3",
"@react-native-community/cli-platform-android": "15.1.3",
"@react-native-community/cli-platform-ios": "15.1.3",
```
