### ISSUE TITLE
Support for timezoneOffsetInMinutes in Android

### ISSUE THREAD

**Issue by StarryFire** [react-native-datetimepicker/datetimepicker#284]
# Feature request

## Why it is needed

Our app uses in-app timezone rather than the device's timezone. So we need to set the timezone offset in datetime pickers in android like we do for iOS datetime pickers.

### Code sample

```
<DateTimePicker
     ...
     timezoneOffsetInMinutes={30}
    ...
/>
```

**Comment by Quelu** [comment]
Hello @StarryFire 
Did you find any solution or workaround for this?

**Comment by StarryFire** [comment]
@Quelu Yup, i started using this library instead https://github.com/henninghall/react-native-date-picker

**Comment by billnbell** [comment]
This is fixed. Can we lok at merging, or give me some feedback?

https://github.com/billnbell/datetimepicker

**Comment by bobdepreziz** [comment]
This is still not working at my end. Any value I specify in timeZoneOffsetInMinutes results in the same offset, it is not working as expected. Can someone verify? I tried it with this package: https://github.com/henninghall/react-native-date-picker, there  it works fine.

Thanks

**Comment by abhittal** [comment]
@bobdepreziz It's not working at my end as well. I tried specifying many values in timeZoneOffsetInMinutes but always get the UTC time in the time picker. Can you suggest me how can I select time relative to my device's timezone?

**Comment by tanjoash** [comment]
> @bobdepreziz It's not working at my end as well. I tried specifying many values in timeZoneOffsetInMinutes but always get the UTC time in the time picker. Can you suggest me how can I select time relative to my device's timezone?

Looking for a solution to this as well. Not a big issue but isn't very pleasant. haha! seems to be a known issue as seen here https://github.com/react-native-datetimepicker/datetimepicker/pull/431. Just be patient and happy coding!

**Comment by vonovak** [comment]
closing as this is implemented, see in readme. There are some bugs, but it's pointless for this to remain open.
