### ISSUE TITLE
Dialog opens twice on Android

### ISSUE THREAD

**Issue by Niore** [react-native-datetimepicker/datetimepicker#54]
If i open the Datepicker it opens twice on Android. I select in the first Dialog a date. then the same dialog opens again and i have to select a date again . After the second time it will accept the input. Can someone help me?

Thats the code of the component. Most of the components are just for styling:

```
const DatePickerInput = ({
  inputName,
  locale,
  labelKey,
  max,
  min,
}) => {
  const { values, setFieldValue } = useFormikContext();
  const [t] = useTranslation('validatedTextInput');
  const [showDatePicker, setShowDatePicker] = useState(false);
  const initialDate = values[inputName] || new Date();
  const [selectedDate, setSelectedDate] = useState(moment(initialDate).toDate());
  const datePlaceholderKey = 'datePlaceholder';
  return (
    <DatePickerContainer>
      <DatePickerLabel>
        {t(labelKey)}
      </DatePickerLabel>
      <DatePickerButtonContainer>
        <DatePickerButton
          onPress={() => setShowDatePicker(!showDatePicker)}
        >
          <DatePickerButtonText>
            {selectedDate
              ? moment(selectedDate).format('L')
              : t(datePlaceholderKey)}
          </DatePickerButtonText>
          <DatePickerButtonImage source={Calendar} />
        </DatePickerButton>
      </DatePickerButtonContainer>
      {
        showDatePicker && (
          <DateTimePicker
            mode="date"
            display="spinner"
            value={selectedDate}
            onChange={(event, value) => {
              setFieldValue(inputName, value);
              setShowDatePicker(!showDatePicker);
              // setSelectedDate(value);
            }}
            maximumDate={max}
            minimumDate={min}
            locale={locale}
          />
        )
      }
    </DatePickerContainer>
  );
};
```
Thx for your help

**Comment by tranhoangduong1994** [comment]
Did you resolve this problem @Niore?
I'm having a similar issue :/

**Comment by Niore** [comment]
no still got no solution for it.

**Comment by crcass** [comment]
Have you tried `setShowDatePicker(Platform.OS === 'ios' ? true : false);`?

**Comment by vovka-s** [comment]
I fixed this problem by closing the picker before handling it's value.
Swap `setFieldValue` and `setShowDatePicker` into `onChange` handler
```
onChange={(event, value) => {
    setShowDatePicker(!showDatePicker);
    setFieldValue(inputName, value);
   // setSelectedDate(value);
}}
```
Hope this will work

**Comment by vancepope** [comment]
@vovka-s I've been scratching my head all day on this one, thank you!

**Comment by mefjuu** [comment]
Another solution is just creating a memoized wrapper for <DateTimePicker /> to avoid render phase of native component:
`const MemoizedDateTimePicker = React.memo((props) => <DateTimePicker {...props} />)`

**Comment by renanborgez** [comment]
It is also happening in iOS with version `"@react-native-community/datetimepicker": "^2.1.0",`

**Comment by androdri1998** [comment]
I fixed it with the following code:

`const [state, setState] = useState({
    date: new Date(),
    mode: 'date',
    show: false
  });

  const onChange = (event, selectedDate) => {
    const currentDate = selectedDate || state.date;

    setState({...state, date: currentDate, show: false});
  };

  const showPicker = currentMode => {
    setState({...state, show: true});
  };

  { state.show && 
    (
        <DateTimePicker
          testID="dateTimePicker"
          timeZoneOffsetInMinutes={0}
          value={state.date}
          mode={state.mode}
          is24Hour={true}
          display="default"
          onChange={onChange}
        />
      ) 
  }
`

**Comment by nisiybr** [comment]
> The problem is because of the rerender queue when using useState hooks explained here
> https://stackoverflow.com/a/54120412
> 
> To implicitly order the rerenders and avoid a second datepicker just do
> 
> ```js
> onChange={(event, value) => {
>  setShowDatePicker(Platform.OS === 'ios'); // first state update hides datetimepicker
>  setFieldValue(inputName, value);
>  setSelectedDate(value);
> }}
> ```
> 
> To be more explicit I suggest the useStateWithCallback hook created by @rwieruch here
> https://github.com/the-road-to-learn-react/use-state-with-callback/blob/master/src/index.js
> 
> And replace your current selectedDate state hook with the following:
> 
> ```js
> const [selectedDate, setSelectedDate] = useStateWithCallback(
>     initialDate,
>     () => setShowDatePicker(Platform.OS === 'ios'),
> ); 
> ```
> 
> With this you no longer need to set the showDatePicker state onChange() so just this:
> 
> ```js
> onChange={(event, value) => {
>  setFieldValue(inputName, value);
>  setSelectedDate(value);
> }}
> ```

Works like a charm.
Thanks!

**Comment by emilmammadov** [comment]
I found the solution. My OnChange method was like yours. You have to handle `event` inside `onChange`.  My code was like that before: 
```
onChange={(event, text)=>{
    this.setState({ date: text });
    this.setState({ isDateOn: false });
}}

```
And I changed it to that. It's working...
```
onChange={(event, text)=>{
    if (event.type === 'set') {
        this.setState({ date: text });
    }
    this.setState({ isDateOn: false });
}}
```

And I have a condition that simply like below: 
```
{this.state.isDateOn ? 
    <DateTimePicker
        .../> : <View/>
}
```

**Comment by odradek123** [comment]
For anyone who the above solution didn't work for, I was having an identical issue. Spent 3 days trying to figure it out and eventually realised it was caused by the debugger. Stopping debug fixed the issue for me.

**Comment by Temirtator** [comment]
sorry but, as for me, there is too many crutches in library. problem should be fix by developers

**Comment by sackda75** [comment]
I'm having the same issue. I've read all the responses but it doesn't help me. Can anyone help me ? Thanks.


import React, { useState } from "react"
import { View, StyleSheet, Text, TouchableOpacity } from "react-native"
import DateTimePickerModal from "react-native-modal-datetime-picker"
import moment from 'moment'
import 'moment/locale/fr'

const App = () => {

  const [isDatePickerVisible, setDatePickerVisibility] = useState(false)

  const [chosenDate, setChosenDate] = useState('')

  const handleConfirm = (datetime) => {
    console.log("A date has been picked: ", datetime)
    setChosenDate(moment(datetime).format('dddd Do MMMM YYYY à HH:mm'))
    hideDatePicker()
  }

  const showDatePicker = () => {
    setDatePickerVisibility(true)
  }

  const hideDatePicker = () => {
    setDatePickerVisibility(false)
  }
  

  return (
    <View style={styles.container}>

      <Text style={styles.displayDate}>{chosenDate}</Text>

      <TouchableOpacity style={styles.buttonStyle} onPress={showDatePicker}>
          <Text style={styles.buttonFont}>Select a date and time</Text>
      </TouchableOpacity>

      <DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="datetime"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        display="default"
      />

    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffff',
    alignItems: 'center',
    justifyContent: 'center'
  },
  displayDate: {
    marginVertical: 20,
    fontSize: 20,
    fontWeight: 'bold',
    color: '#8e44ad'
  },
  buttonStyle: {
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 30,
    marginRight: 30,
    backgroundColor: '#FDA7DF',
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#1B1464',
    width: 250
  },
  buttonFont: {
    textAlign: 'center',
    color: '#ffff',
    fontWeight: 'bold',
    fontSize: 20
  }
})

export default App

**Comment by sackda75** [comment]
I'm having the same issue with DateTimePickerModal. I've read all the comments but it can't fix it.  Can anyone help me ? Thanks

import React, { useState } from "react"
import { View, StyleSheet, Text, TouchableOpacity } from "react-native"
import DateTimePickerModal from "react-native-modal-datetime-picker"
import moment from 'moment'
import 'moment/locale/fr'


const App = () => {

  const [isDatePickerVisible, setDatePickerVisibility] = useState(false)

  const [chosenDate, setChosenDate] = useState('')

  const handleConfirm = (datetime) => {
    console.log("A date has been picked: ", datetime)
    setChosenDate(moment(datetime).format('dddd Do MMMM YYYY à HH:mm'))
    hideDatePicker()
  }

  const showDatePicker = () => {
    setDatePickerVisibility(true)
  }

  const hideDatePicker = () => {
    setDatePickerVisibility(false)
  }

  return (
    <View style={styles.container}>

      <Text style={styles.displayDate}>{chosenDate}</Text>

      <TouchableOpacity style={styles.buttonStyle} onPress={showDatePicker}>
          <Text style={styles.buttonFont}>Select a date and time</Text>
      </TouchableOpacity>

      <DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="datetime"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        display="default"
      
      />

    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffff',
    alignItems: 'center',
    justifyContent: 'center'
  },
  displayDate: {
    marginVertical: 20,
    fontSize: 20,
    fontWeight: 'bold',
    color: '#8e44ad'
  },
  buttonStyle: {
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 30,
    marginRight: 30,
    backgroundColor: '#FDA7DF',
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#1B1464',
    width: 250
  },
  buttonFont: {
    textAlign: 'center',
    color: '#ffff',
    fontWeight: 'bold',
    fontSize: 20
  }
})

export default App

**Comment by vovka-s** [comment]
try that
```
const handleConfirm = (datetime) => {
   hideDatePicker() //must be first
   console.log("A date has been picked: ", datetime)  
   setChosenDate(moment(datetime).format('dddd Do MMMM YYYY à HH:mm'))
}
```
If not, try to use `onChange` callback instead of `onConfirm`
It works for me

**Comment by sackda75** [comment]
> const handleConfirm = (datetime) => {
>    hideDatePicker() //must be first
>    console.log("A date has been picked: ", datetime)  
>    setChosenDate(moment(datetime).format('dddd Do MMMM YYYY à HH:mm'))
> }

Thank you very much ! It works !

**Comment by vishwa1937** [comment]
> try that
> 
> ```
> const handleConfirm = (datetime) => {
>    hideDatePicker() //must be first
>    console.log("A date has been picked: ", datetime)  
>    setChosenDate(moment(datetime).format('dddd Do MMMM YYYY à HH:mm'))
> }
> ```
> 
> If not, try to use `onChange` callback instead of `onConfirm`
> It works for me

@ vovka-s Thank you very much . It worked for me, you saved my day.

**Comment by sjonchhe** [comment]
> For anyone who the above solution didn't work for, I was having an identical issue. Spent 3 days trying to figure it out and eventually realised it was caused by the debugger. Stopping debug fixed the issue for me.

This kind of solved it for me

**Comment by Luckygirlllll** [comment]
> For anyone who the above solution didn't work for, I was having an identical issue. Spent 3 days trying to figure it out and eventually realised it was caused by the debugger. Stopping debug fixed the issue for me.

wow, that helped me as well, I spent about 4 hours trying to figure out what's wrong with the picker!

**Comment by MorenoMdz** [comment]
> The problem is because of the rerender queue when using useState hooks explained here
> https://stackoverflow.com/a/54120412
> 
> To implicitly order the rerenders and avoid a second datepicker just do
> 
> ```js
> onChange={(event, value) => {
>  setShowDatePicker(Platform.OS === 'ios'); // first state update hides datetimepicker
>  setFieldValue(inputName, value);
>  setSelectedDate(value);
> }}
> ```
> 
> To be more explicit I suggest the useStateWithCallback hook created by @rwieruch here
> https://github.com/the-road-to-learn-react/use-state-with-callback/blob/master/src/index.js
> 
> And replace your current selectedDate state hook with the following:
> 
> ```js
> const [selectedDate, setSelectedDate] = useStateWithCallback(
>     initialDate,
>     () => setShowDatePicker(Platform.OS === 'ios'),
> ); 
> ```
> 
> With this you no longer need to set the showDatePicker state onChange() so just this:
> 
> ```js
> onChange={(event, value) => {
>  setFieldValue(inputName, value);
>  setSelectedDate(value);
> }}
> ```

Thank you that solved for me. 
I have it set this way if anybody needs a Modal component that supports both OS.
[https://gist.github.com/MorenoMdz/4b144eac9e64aa9e931bc30f9b5b9409](url)

**Comment by rakefetWorkiz** [comment]
I tried all the above, and none helped me. 
But using 
```
onHide={() => setShowDatePicker(false)}
```
worked like a charm :)

**Comment by jkdc** [comment]
Hi!
for me work this example when you have two DateTimePicker in same page.


`    const showTimepicker = (event: any) => {
        event.preventDefault()
        setShow(true);
    };
    <TextLinkButton onPress={(event) => showTimepicker(event)} label={label} />`

I hope it works for you. A greeting!

**Comment by rossenv** [comment]
> I tried all the above, and none helped me.
> But using
> 
> ```
> onHide={() => setShowDatePicker(false)}
> ```
> 
> worked like a charm :)

react-native-datetimepicker has no onHide method

**Comment by ChanakaChampSoft** [comment]
> I fixed this problem by closing the picker before handling it's value.
> Swap `setFieldValue` and `setShowDatePicker` into `onChange` handler
> 
> ```
> onChange={(event, value) => {
>     setShowDatePicker(!showDatePicker);
>     setFieldValue(inputName, value);
>    // setSelectedDate(value);
> }}
> ```
> 
> Hope this will work

working !! Tada !!

**Comment by parth-koshta** [comment]
> I fixed this problem by closing the picker before handling it's value.
> Swap `setFieldValue` and `setShowDatePicker` into `onChange` handler
> 
> ```
> onChange={(event, value) => {
>     setShowDatePicker(!showDatePicker);
>     setFieldValue(inputName, value);
>    // setSelectedDate(value);
> }}
> ```
> 
> Hope this will work

Thanks @vovka-s

**Comment by hiepnh610** [comment]
> I fixed this problem by closing the picker before handling it's value.
> Swap `setFieldValue` and `setShowDatePicker` into `onChange` handler
> 
> ```
> onChange={(event, value) => {
>     setShowDatePicker(!showDatePicker);
>     setFieldValue(inputName, value);
>    // setSelectedDate(value);
> }}
> ```
> 
> Hope this will work

Thank you so much!!!
You saved my life.

**Comment by daheeahn** [comment]
> Another solution is just creating a memoized wrapper for avoid render phase of native component:
> `const MemoizedDateTimePicker = React.memo((props) => <DateTimePicker {...props} />)`

Thanks! It works.

**Comment by kapilwhaval** [comment]
I tried this workaround. Works fine.

```
const DTPicker = ({ mode, onChange, value, placeholder, label,}) => {

    const [show, setShow] = useState(false);
    
    const handleDate = (e) => {
        if (e.nativeEvent.timestamp) onChange(e.nativeEvent.timestamp)
        setShow(Platform.OS === 'ios')
    }
    
    return <View>
        <TextInput placeHolder={placeholder} label={label} onFocus={() => setShow(true)} value={value} />
        {React.useMemo(() => {
            return show && <DateTimePicker
                value={new Date()}
                mode={mode}
                display="default"
                onChange={handleDate}
            />
        }, [show])}
    </View>
};
```

**Comment by mefjuu** [comment]
> I tried this workaround. Works fine.

Very weird use case for useMemo... Better try to extract it to React.memo'ized component

**Comment by kapilwhaval** [comment]
> > I tried this workaround. Works fine.
> 
> Very weird use case for useMemo... Better try to extract it to React.memo'ized component

Yes. We can refactor the component as you are saying. I have just added it here in single function, so that everyone can understand

**Comment by yayidg22** [comment]
I fixed this problem
onConfirm={selecteddate => {
setPickerVisible(false);
setDate(selecteddate);
} }

 to

 onConfirm={(selectedDate) => {
setPickerVisible(false);
setDate(selecteddate);
 } }

**Comment by DavidBrear** [comment]
I had this issue with the dialog showing up again after I'd selected the date value. My solution that worked is:

```
const [show, setShow] = React.useState<boolean>(false);
const [birthday, setBirthday] = React.useState<string | undefined>(undefined);
const onChangeDate = useCallback((event, selectedDate) => {
    setBirthday(selectedDate);
    setShow(false);
  }, []);

// in the render
{show && (
                <View>
                  <DateTimePicker
                    testID="dateTimePicker"
                    maximumDate={
                      new Date(
                        moment().subtract(13, "years").format("yyyy-MM-DD"),
                      )
                    }
                    value={
                      birthday
                        ? new Date(birthday)
                        : new Date(
                            moment().subtract(13, "years").format("yyyy-MM-DD"),
                          )
                    }
                    mode="date"
                    display="default"
                    onChange={(e, v) => {
                      setShow(Platform.OS === "ios");
                      onChangeDate(e, v);
                    }}
                  />
                </View>
              )}
``` hope this helps!

**Comment by sktan810** [comment]
Still not able to fix this, by following the comment [](https://github.com/react-native-datetimepicker/datetimepicker/issues/54#issuecomment-553826672) and also [](https://github.com/react-native-datetimepicker/datetimepicker/issues/54#issuecomment-614005465).

Any solution or any method on fixing this ? Still facing dialog opens twice on Android.

**Comment by Vigneshacme** [comment]
> I fixed this problem by closing the picker before handling it's value.
> Swap `setFieldValue` and `setShowDatePicker` into `onChange` handler
> 
> ```
> onChange={(event, value) => {
>     setShowDatePicker(!showDatePicker);
>     setFieldValue(inputName, value);
>    // setSelectedDate(value);
> }}
> ```
> 
> Hope this will work

thank you! it worked

**Comment by renatomh** [comment]
The suggested solution of closing the picker before anything else does not work for me. Also, I can't change the selected date.

What I believe it's happening in my case, is that due to the fact that two pickers are open, whenever I try selecting the new date on the visible picker, the picker behind it forces the date to be the previous selected value.

Here's what happens on my code when:
- Closing the picker before setting the value:
  - Android emulator, when I close the picker, the second picker just pops and disappear, date does not change;
  - Android Physical Device: when I close the picker, the second picker also gets closed and it's not possible to change the date;
- Setting the value before closing the picker:
  - On the Android emulator, when I close the picker, the second picker just pops and disappear, date does not change;
  - Android Physical Device, when I close the picker, the second picker becomes visible and it's possible to select the date;

Also, what's the default behaivour of 'onChange'? Should it get triggered whenever you click on a new date? Or only after you click 'Ok' to confirm the selected date?
If the first option is the default behaviour, I believe that this method is only getting attached to the 'second' picker, which is not visible at first.

Here's the relevant part of the current code I'm working with:

```typescript
  const [usedAt, setUsedAt] = useState(new Date());
  const [showDatePicker, setShowDatePicker] = useState(false);
  ...

  return (
      ...

      {showDatePicker && (
        <DateTimePicker
          testID="dateTimePicker"
          value={usedAt}
          mode="date"
          is24Hour
          display="default"
          onChange={(e: Event, date?: Date) => {
            setShowDatePicker(Platform.OS === 'ios');
            setUsedAt(date || usedAt);
          }}
        />
      )}
      ...
  )
```

**Comment by renatomh** [comment]
> The suggested solution of closing the picker before anything else does not work for me. Also, I can't change the selected date.
> 
> What I believe it's happening in my case, is that due to the fact that two pickers are open, whenever I try selecting the new date on the visible picker, the picker behind it forces the date to be the previous selected value.
> 
> Here's what happens on my code when:
> 
> * Closing the picker before setting the value:
>   
>   * Android emulator, when I close the picker, the second picker just pops and disappear, date does not change;
>   * Android Physical Device: when I close the picker, the second picker also gets closed and it's not possible to change the date;
> * Setting the value before closing the picker:
>   
>   * On the Android emulator, when I close the picker, the second picker just pops and disappear, date does not change;
>   * Android Physical Device, when I close the picker, the second picker becomes visible and it's possible to select the date;
> 
> Also, what's the default behaivour of 'onChange'? Should it get triggered whenever you click on a new date? Or only after you click 'Ok' to confirm the selected date?
> If the first option is the default behaviour, I believe that this method is only getting attached to the 'second' picker, which is not visible at first.
> 
> Here's the relevant part of the current code I'm working with:
> 
> ```ts
>   const [usedAt, setUsedAt] = useState(new Date());
>   const [showDatePicker, setShowDatePicker] = useState(false);
>   ...
> 
>   return (
>       ...
> 
>       {showDatePicker && (
>         <DateTimePicker
>           testID="dateTimePicker"
>           value={usedAt}
>           mode="date"
>           is24Hour
>           display="default"
>           onChange={(e: Event, date?: Date) => {
>             setShowDatePicker(Platform.OS === 'ios');
>             setUsedAt(date || usedAt);
>           }}
>         />
>       )}
>       ...
>   )
> ```

I've managed to get it to work now. Basically, I had to create a function with the 'useCallback' hook to deal with the date selection event like so:

```typescript
  const handleDateChange = useCallback(
    (event: Event, date: Date | undefined) => {
      if (Platform.OS === 'android') {
        setShowDatePicker(false);
      }
      if (date) setUsedAt(date);
    },
    [],
  );

  return (
      ...

      {showDatePicker && (
        <DateTimePicker
          testID="dateTimePicker"
          value={usedAt}
          mode="date"
          is24Hour
          display="default"
          onChange={handleDateChange}
        />
      )}
      ...
  )
```

**Comment by carlossison75** [comment]
I'm 2 years late and I don't know if this is fixed already since I didn't read everything, but whoever still having this issue, just close the modal first before setting the new date.

**Comment by vonovak** [comment]
Hello 👋 ,
this issues should be resolved in https://github.com/react-native-datetimepicker/datetimepicker/pull/574

With that, I'm closing the issue,
Thank you! 🙂

**Comment by Shail-Patel-1** [comment]
> try that
> 
> ```
> const handleConfirm = (datetime) => {
>    hideDatePicker() //must be first
>    console.log("A date has been picked: ", datetime)  
>    setChosenDate(moment(datetime).format('dddd Do MMMM YYYY à HH:mm'))
> }
> ```
> 
> If not, try to use `onChange` callback instead of `onConfirm` It works for me

Thank you so much 
this work like charm 
i was struggling from many days

**Comment by chefk5** [comment]
> try that
> 
> ```
> const handleConfirm = (datetime) => {
>    hideDatePicker() //must be first
>    console.log("A date has been picked: ", datetime)  
>    setChosenDate(moment(datetime).format('dddd Do MMMM YYYY à HH:mm'))
> }
> ```
> 
> If not, try to use `onChange` callback instead of `onConfirm` It works for me

Still works!

**Comment by Suliman-A** [comment]
> DatePickerModal

which debugger do you mean exactly?

**Comment by iamemiliano** [comment]
I hope you are doing well. I have a problem with react native on Android. In IOS, it works well but when i open a componant who includes a DataTimePicker in Android, it automatically shows me the DatatimePicker. Do you know what the problem is in my code ?

                 <View style={styles.dateContainer}>
                    <Text style={styles.customLabelDate}>
                        Date de naissance
                    </Text>
                    <DateTimePicker
                        testID="dateTimePicker"
                        value={stateForm.dateOfBirth}
                        mode="date"
                        is24Hour={true}
                        display="calendar"
                        onChange={(event, value) => {
                            dispatchStateForm({
                                type: UPDATE,
                                payload: { name: "dateOfBirth", value: value },
                            });
                        }}
                        style={styles.dateTime}
                        locale="fr-FR"
                        textColor="red"
                    />
                </View>

This is the result :

![image](https://user-images.githubusercontent.com/97671466/195999987-a400c079-f869-4f65-a4a0-6c9ba40d54e1.png)

Thanks in advance.

**Comment by chefk5** [comment]
@iamemiliano you need to wrap it with a state and show it according to it. Have a look in the [example](https://github.com/react-native-datetimepicker/datetimepicker/blob/master/example/App.js) ` {show && (
                <DateTimePicker
                  testID="dateTimePicker"
                  timeZoneOffsetInMinutes={tzOffsetInMinutes}
                  minuteInterval={interval}
                  maximumDate={maximumDate}
                  minimumDate={minimumDate}
                  value={date}
                  mode={mode}
                  is24Hour
                  display={display}
                  onChange={onChange}
                  textColor={textColor || undefined}
                  accentColor={accentColor || undefined}
                  neutralButtonLabel={neutralButtonLabel}
                  disabled={disabled}
                />
              )}`

**Comment by ShizaSiddiqui** [comment]
setShowCalendarToDate(Platform.OS === 'ios' ? true : false); //first line of onChange function
 
This will solve the android issue. But if you do not do this, iOS will start misbehaving. For example, if you set either month, year, or date, the iOS picker will disappear before letting you select all three.

**Comment by Onikiri1** [comment]
hi, im working on a task app, and when i use te DateTimePicker, it opens twice and doesnt show the selected date.
i've tried all above and nothing really worked,
this is what im working on 
`   <DateTimePicker
          value={date}
          mode={"time"}
          is24Hour={true}
          onChange={(event, value) => {
            setShowDatePicker(!showDatePicker);
            setDate(selectedDate); }}
          style={{width: "80%"}}
        />
      `

**Comment by Shail-Patel-1** [comment]
This is what you might have done 

```
 const handleConfirm = selectedDateFromPicker => {
    Keyboard.dismiss();
    setDate(prevState => ({
      ...prevState,
      [type]: Helper.convertToIsoDateString(selectedDateFromPicker),
    }));
   **hideDatePicker();** --> _HERE_
```

You should do something like this

```
 const handleConfirm = selectedDateFromPicker => {
  **hideDatePicker();** --> _HERE_
    Keyboard.dismiss();
    setDate(prevState => ({
      ...prevState,
      [type]: Helper.convertToIsoDateString(selectedDateFromPicker),
    }));
```


You should first hide the date picket than you can do any operations you want
This will work. @Onikiri1

**Comment by R-s-rawat** [comment]
yes same here in deadline stage

**Comment by SadatJubayer** [comment]
If anyone is still facing this issue, you can try this easy fix:

```
const [showDatePicker, setShowDatePicker] = useState(false);

{showDatePicker && (
  <DateTimePicker
    value={new Date()}
    mode={'date'}
    minimumDate={moment().startOf('day').toDate()}
    onChange={(_, newDate) => {
      setShowDatePicker(() => {
        setDate(newDate);
        return false; 
      });
    }}
  />
)}

```

In onChange, setShowDatePicker's callback function updates the date and then updates the showdatePicker state by returning false.

**Comment by 0tii** [comment]
None of the ones here worked for me with the timepicker. Timepicker opens 2 modals on android.
